baseURL = "https://obsanmuzemil.com/"
title = "Obsan Muzemil"
paginate = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production" # to enable opengraph, twitter-cards, and schema.
  title = "Obsan Muzemil"
  description = "Cybersecurity Professional and Blogger"
  keywords = ["Cybersecurity", "Portfolio", "PaperMod", "Blog"]
  author = "Obsan Muzemil"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my website where I share my journey in cybersecurity and technology."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/OBIchance"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/obsan-muzemil-95b876153/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 45

  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/archives/"
    weight = 25

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 20

  [[menu.main]]
    identifier = "write-ups"
    name = "Write-Ups"
    url = "/posts/write-ups/"
    weight = 35

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true

[markup]
  [markup.highlight]
    noClasses = false
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
